# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8 # Uses docker to run our tests...
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test
